id: PBCBBD488
initial_creation_type: input
source_metadata:
  title: Confession Series
  language: it
  description: 'Lotsawa House presents the following texts related to the practice
    of confession (bshags pa):'
  volume:
    78b11f24c77d40168224933821ffbc0e:
      title: Daily Confession (from the Vajrapañjara Tantra)
      parent: Canonical Works
    06db897355ff44d2a6835714885f837d:
      title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
      parent: Canonical Works
    6a5bcff72da940938a63a5dc79d2d508:
      title: The Lament of Rudra
      parent: Practices
    069d1a8197474c02a9b430527c2a6ccb:
      title: The Noble Sūtra of the Teaching on the Four Factors
      parent: Canonical Works
    227bff385c1d43ed8b92e900aef6ff3b:
      title: The Ultimate Inexpressible Confession (Yeshe Kuchokma)
      parent: Canonical Works
    a943e505482848aead4044339047df57:
      title: Verses of Confession 'Düsum Deshekma'
      parent: Canonical Works
    41b809394f65425295e04b77c5b38442:
      title: Guide to the Practice of Narak Kong Shak
      parent: Commentaries
    a9d7b4a6eb7a4ece92928b15913394d6:
      title: A Topical Outline of the General Confession Spoken by the Five Great
        Sages
      parent: Outlines
    b15e26fb9e1f4cb6a3685183d43153e2:
      title: Root Downfalls of the Vajra Vehicle
      parent: Practices
    e9455be8648c41a285c7f48e52d5fa17:
      title: The Inexpressible, Ultimate Confession (Yeshe Kuchokma)
      parent: Practices
    c7b9d029a8984497a28c50bfd5f9b792:
      title: Heart of Vajrasattva—The Heart of Confession, the King of Purification
        Practices, from 'The Immaculate Secret Vajrasattva'
      parent: Practices
    7990e037a373497ca0b3609b6e89e995:
      title: 'Emptying the Hells from their Very Depths: The Sovereign Practice for
        the Confession of all Impairments and Breakages of Vows and all Negative Actions
        and Obscurations'
      parent: Practices
    ebdcc90338724629963c4506546e242e:
      title: A Practice of Fulfilment and Confession to an Ocean of Oath-bound Protectors
      parent: Practices
    38ffc7af3dc641029c828d3ef798463b:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Practices
    6673cbd6471b4fb5a1b5cb05599b045f:
      title: A Discourse on the Confession of Harmful Deeds Spoken by Yama Dharmarāja
        to Karma Chakme
      parent: Practices
    ddd923f941a2453985172a28957783a1:
      title: Brief Confession to the Earth Lords
      parent: Practices
    18120e5c08d44e44a1eda4fe31617cfa:
      title: A Method of Confessing and Pledging through the Four Powers
      parent: Practices
    3e60b4579b5740d388c48f05236a757c:
      title: Rays of Moonlight to Dispel the Darkness of Misdeeds
      parent: Practices
    c4c16176e6cc46faaeaf72d64e6cacef:
      title: Method of Confession based on the Four Powers
      parent: Practices
    813c8467a4ee4b968a8727d095b00111:
      title: The Sovereign of Confessions for all Impairments and Breakages, Extracted
        from the Rampant Elephant Tantra
      parent: Practices
    724c1b20ca394ab69547da4f31f60053:
      title: A Prayer to Recognize My Own Faults and Keep in Mind the Objects of Refuge
      parent: Prayer
created_at: '2022-03-01T03:17:51.739646'
last_modified_at: '2022-03-01T03:17:51.739649'
